version: '3.8'

services:
  flask_app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FASTAPI_URL=http://fastapi_app:8000
    volumes:
      - ./flask_app:/app
    depends_on:
      - fastapi_app
    networks:
      - amalfi_network

  fastapi_app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP_URL=http://flask_app:5000/api/notify
    volumes:
      - ./fastapi_app:/app
    networks:
      - amalfi_network

networks:
  amalfi_network:
    driver: bridge
