version: '3.8'

services:
  flask_app:
    container_name: results_flask_app
    restart: always
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FASTAPI_URL=http://results_fastapi_app:8000
    volumes:
      - ./flask_app:/app
    depends_on:
      - fastapi_app
    networks:
      - amalfi_network
    expose:
      - 5000

  fastapi_app:
    container_name: results_fastapi_app
    restart: always
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    environment:
      - FLASK_APP_URL=http://results_flask_app:5000/api/notify
    volumes:
      - ./fastapi_app:/app
      - fastapi_data:/app/data
    networks:
      - amalfi_network
    expose:
      - 8000

networks:
  amalfi_network:
    external: true

volumes:
  fastapi_data:
    driver: local
